#App config values
productservice.type = FakeStoreProductService
server.port = 7500
app.base.url = /products

#FakeStore config values
fakestore.api.url = https://fakestoreapi.com
fakestore.api.paths.products = /products

#DB config
spring.jpa.hibernate.ddl-auto = update
spring.datasource.url = ${DATABASE_URL}
spring.datasource.username = ${DATABASE_USERNAME}
#spring.datasource.password = ThePassword
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
spring.jpa.show-sql = true

# Flyway should be enabled (add these lines)
#spring.flyway.enabled=true
#spring.flyway.locations=classpath:db/migration
#spring.flyway.baseline-on-migrate=true

spring.security.oauth2.resourceserver.jwt.issuer-uri = ${AUTH_SERVER_ISSUER_URI}