apiVersion: v1
kind: ConfigMap
metadata:
  name: product-config

data:
  DATABASE_URL: "jdbc:mysql://host.minikube.internal:3306/backendSample"
  DATABASE_USERNAME: "backendSample"
  AUTH_SERVER_ISSUER_URI: "http://host.minikube.internal:7600"
  SERVER_PORT: "7500"
  ELASTICSEARCH_URI: "http://host.minikube.internal:9200"
  EUREKA_URI: "http://host.minikube.internal:8761/eureka"
  REDIS_HOST: "host.minikube.internal"